//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDumpApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDumpSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarDumpSet()
        {
            this.SetItems = new HashSet<SetItem>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModelId { get; set; }
        public string Description { get; set; }
        public int Year { get; set; }
        public string PostedUserID { get; set; }
    
        public virtual AutoModel AutoModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SetItem> SetItems { get; set; }
    }
}
