//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDumpApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDump
    {
        public int Id { get; set; }
        public int AutoModelId { get; set; }
        public int Year { get; set; }
        public int ModuleID { get; set; }
        public int MemoryTypeID { get; set; }
        public string ModuleNumber { get; set; }
        public string FileURL { get; set; }
        public string Description { get; set; }
    
        public virtual AutoModel AutoModel { get; set; }
        public virtual MemoryType MemoryType { get; set; }
        public virtual Module Module { get; set; }
    }
}
