//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDumpApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDump
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarDump()
        {
            this.SetItems = new HashSet<SetItem>();
        }
    
        public int Id { get; set; }
        public int AutoModelId { get; set; }
        public int Year { get; set; }
        public int ModuleID { get; set; }
        public int MemoryTypeID { get; set; }
        public string ModuleNumber { get; set; }
        public string FileURL { get; set; }
        public string Description { get; set; }
        public bool Checked { get; set; }
        public string Pic1Url { get; set; }
        public string Pic2Url { get; set; }
        public string PostedUserID { get; set; }
        public int AccessLevelID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual AutoModel AutoModel { get; set; }
        public virtual MemoryType MemoryType { get; set; }
        public virtual Module Module { get; set; }
        public virtual CarDumpAccessLevel CarDumpAccessLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SetItem> SetItems { get; set; }
    }
}
