//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDumpApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetItem
    {
        public int Id { get; set; }
        public int CarDumpSetID { get; set; }
        public int CarDumpID { get; set; }
    
        public virtual CarDump CarDump { get; set; }
        public virtual CarDumpSet CarDumpSet { get; set; }
    }
}
