//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDumpApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoredFile
    {
        public int Id { get; set; }
        public byte[] FileData { get; set; }
        public string OriginalFileName { get; set; }
        public Nullable<int> ParentCarDumpRecordId { get; set; }
    }
}
